# Importing Modules

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

### READING DATASET

In [4]:
data = pd.read_csv('rainfall.csv')
data.head()

   Rainfall - (MM)   Year     Month
0          40.4258   1901   January
1          12.3022   1901  February
2          25.5119   1901     March
3          14.2942   1901     April
4          38.3046   1901       May

In [5]:
data.describe()

       Rainfall - (MM)         Year
count      1392.000000  1392.000000
mean         25.142392  1958.500000
std          22.239632    33.497105
min           0.105840  1901.000000
25%           9.586635  1929.750000
50%          19.653750  1958.500000
75%          33.753075  1987.250000
max         154.055000  2016.000000