# Expolatory Data Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Exploring Data

In [59]:
# Reading DataSet
data = pd.read_csv('covid.csv')
data.head()

         Date  Deaths  Recoveries  Total
0  2020-02-26     NaN         NaN      2
1  2020-02-29     NaN         NaN      4
2  2020-03-03     NaN         NaN      5
3  2020-03-04     NaN         NaN      5
4  2020-03-05     NaN         NaN      6

In [60]:
data.shape

(594, 4)

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        594 non-null    object
 1   Deaths      579 non-null    float64
 2   Recoveries  589 non-null    float64
 3   Total       594 non-null    int64
dtypes: float64(2), int64(1), object(1)
memory usage: 18.7+ KB

In [62]:
data.describe()

             Deaths    Recoveries         Total
count    579.000000  5.890000e+02  5.940000e+02
mean   12063.350604  4.871839e+05  5.358178e+05
std     8607.483741  3.590567e+05  3.830745e+05
min        2.000000  1.000000e+00  2.000000e+00
25%     6104.500000  2.488730e+05  2.765500e+05
50%    10258.000000  4.238920e+05  4.683520e+05
75%    20502.500000  8.203740e+05  8.997810e+05
max    28280.000000  1.210897e+06  1.265047e+06

In [63]:
# Column names
data.columns

Index(['Date', 'Deaths', 'Recoveries', 'Total'], dtype='object')

In [64]:
# Unique Values
data.nunique()

Date          594
Deaths        577
Recoveries    578
Total         593
dtype: int64

In [65]:
data['Deaths'].unique()

array([       nan, 2.0000e+00, 3.0000e+00, 5.0000e+00, 6.0000e+00,
       7.0000e+00, 8.0000e+00, 9.0000e+00, 1.1000e+01, 1.3000e+01,
       1.8000e+01, 2.5000e+01, 2.6000e+01, 3.1000e+01, 3.5000e+01,
       3.6000e+01, 4.1000e+01, 4.5000e+01, 5.1000e+01, 5.5000e+01,
       6.1000e+01, 6.3000e+01, 6.6000e+01, 8.6000e+01, 9.1000e+01,
       9.3000e+01, 9.6000e+01, 1.1100e+02, 1.2800e+02, 1.3500e+02,
       1.4400e+02, 1.6800e+02, 1.7600e+02, 2.0100e+02, 2.1200e+02,
       2.3500e+02, 2.5300e+02, 2.6900e+02, 2.8100e+02, 2.9200e+02,
       3.1200e+02, 3.4300e+02, 3.8500e+02, 4.1700e+02, 4.4000e+02,
       4.6200e+02, 4.8600e+02, 5.1400e+02, 5.4400e+02, 5.8500e+02,
       5.9900e+02, 6.3600e+02, 6.5900e+02, 6.6700e+02, 7.2400e+02,
       7.3700e+02, 7.7000e+02, 8.0300e+02, 8.3400e+02, 8.7300e+02,
       9.0300e+02, 9.3900e+02, 9.8500e+02, 1.0170e+03, 1.0670e+03,
       1.1010e+03, 1.1330e+03, 1.1670e+03, 1.1970e+03, 1.2250e+03,
       1.2600e+03, 1.3170e+03, 1.3950e+03, 1.4830e+03, 1.5430e+03,
       1.6210e+03, 1.6880e+03, 1.7700e+03, 1.8380e+03, 1.9350e+03,
       2.0020e+03, 2.0670e+03, 2.1720e+03, 2.2550e+03, 2.3560e+03,
       2.4630e+03, 2.5510e+03, 2.6320e+03, 2.7290e+03, 2.8390e+03,
       2.9750e+03, 3.0930e+03, 3.2290e+03, 3.3820e+03, 3.5010e+03,
       3.5900e+03, 3.6950e+03, 3.7550e+03, 3.9030e+03, 3.9620e+03,
       4.0350e+03, 4.1180e+03, 4.1670e+03, 4.3040e+03, 4.3950e+03,
       4.4730e+03, 4.5510e+03, 4.6190e+03, 4.7120e+03, 4.7620e+03,
       4.8390e+03, 4.9220e+03, 4.9830e+03, 5.0580e+03, 5.1230e+03,
       5.1970e+03, 5.2660e+03, 5.3200e+03, 5.3860e+03, 5.4260e+03,
       5.4750e+03, 5.5220e+03, 5.5680e+03, 5.5990e+03, 5.6390e+03,
       5.6770e+03, 5.7090e+03, 5.7630e+03, 5.7870e+03, 5.8220e+03,
       5.8420e+03, 5.8650e+03, 5.8900e+03, 5.9190e+03, 5.9510e+03,
       5.9700e+03, 5.9840e+03, 5.9990e+03, 6.0140e+03, 6.0350e+03,
       6.0520e+03, 6.0680e+03, 6.0820e+03, 6.0970e+03, 6.1120e+03,
       6.1290e+03, 6.1390e+03, 6.1530e+03, 6.1620e+03, 6.1680e+03,
       6.1750e+03, 6.1900e+03, 6.2010e+03, 6.2090e+03, 6.2190e+03,
       6.2310e+03, 6.2350e+03, 6.2440e+03, 6.2550e+03, 6.2670e+03,
       6.2740e+03, 6.2830e+03, 6.2840e+03, 6.2880e+03, 6.2940e+03,
       6.2980e+03, 6.3180e+03, 6.3280e+03, 6.3350e+03, 6.3400e+03,
       6.3420e+03, 6.3450e+03, 6.3500e+03, 6.3590e+03, 6.3650e+03,
       6.3700e+03, 6.3730e+03, 6.3790e+03, 6.3830e+03, 6.3890e+03,
       6.3930e+03, 6.3990e+03, 6.4080e+03, 6.4150e+03, 6.4160e+03,
       6.4200e+03, 6.4240e+03, 6.4320e+03, 6.4370e+03, 6.4440e+03,
       6.4510e+03, 6.4570e+03, 6.4660e+03, 6.4740e+03, 6.4790e+03,
       6.4840e+03, 6.4990e+03, 6.5070e+03, 6.5130e+03, 6.5170e+03,
       6.5230e+03, 6.5350e+03, 6.5440e+03, 6.5520e+03, 6.5580e+03,
       6.5700e+03, 6.5800e+03, 6.5880e+03, 6.6010e+03, 6.6140e+03,
       6.6210e+03, 6.6380e+03, 6.6540e+03, 6.6590e+03, 6.6730e+03,
       6.6920e+03, 6.7020e+03, 6.7150e+03, 6.7270e+03, 6.7360e+03,
       6.7390e+03, 6.7450e+03, 6.7590e+03, 6.7750e+03, 6.7950e+03,
       6.8060e+03, 6.8230e+03, 6.8350e+03, 6.8490e+03, 6.8670e+03,
       6.8930e+03, 6.9230e+03, 6.9430e+03, 6.9680e+03, 6.9770e+03,
       7.0000e+03, 7.0210e+03, 7.0550e+03, 7.0920e+03, 7.1090e+03,
       7.1410e+03, 7.1600e+03, 7.1930e+03, 7.2300e+03, 7.2480e+03,
       7.5610e+03, 7.6030e+03, 7.6620e+03, 7.6960e+03, 7.7440e+03,
       7.8030e+03, 7.8430e+03, 7.8970e+03, 7.9420e+03, 7.9850e+03,
       8.0250e+03, 8.0910e+03, 8.1660e+03, 8.2050e+03, 8.2600e+03,
       8.3030e+03, 8.3610e+03, 8.3980e+03, 8.4870e+03, 8.5470e+03,
       8.6030e+03, 8.6530e+03, 8.7240e+03, 8.7960e+03, 8.8320e+03,
       8.9050e+03, 9.0100e+03, 9.0800e+03, 9.1640e+03, 9.2500e+03,
       9.3300e+03, 9.3920e+03, 9.4740e+03, 9.5570e+03, 9.6680e+03,
       9.7530e+03, 9.8160e+03, 9.8740e+03, 9.9290e+03, 9.9920e+03,
       1.0047e+04, 1.0105e+04, 1.0176e+04, 1.0258e+04, 1.0311e+04,
       1.0350e+04, 1.0409e+04, 1.0461e+04, 1.0511e+04, 1.0558e+04,
       1.0598e+04, 1.0644e+04, 1.0676e+04, 1.0717e+04, 1.0772e+04,
       1.0818e+04, 1.0863e+04, 1.0908e+04, 1.0951e+04, 1.0997e+04,
       1.1055e+04, 1.1103e+04, 1.1157e+04, 1.1204e+04, 1.1247e+04,
       1.1295e+04, 1.1318e+04, 1.1376e+04, 1.1450e+04, 1.1514e+04,
       1.1560e+04, 1.1623e+04, 1.1657e+04, 1.1683e+04, 1.1746e+04,
       1.1802e+04, 1.1833e+04, 1.1886e+04, 1.1914e+04, 1.1967e+04,
       1.2026e+04, 1.2066e+04, 1.2128e+04, 1.2185e+04, 1.2218e+04,
       1.2276e+04, 1.2307e+04, 1.2333e+04, 1.2380e+04, 1.2436e+04,
       1.2488e+04, 1.2527e+04, 1.2563e+04, 1.2601e+04, 1.2617e+04,
       1.2658e+04, 1.2708e+04, 1.2772e+04, 1.2804e+04, 1.2837e+04,
       1.2860e+04, 1.2896e+04, 1.2938e+04, 1.3013e+04, 1.3076e+04,
       1.3128e+04, 1.3166e+04, 1.3205e+04, 1.3227e+04, 1.3281e+04,
       1.3324e+04, 1.3377e+04, 1.3430e+04, 1.3476e+04, 1.3508e+04,
       1.3537e+04, 1.3595e+04, 1.3656e+04, 1.3717e+04, 1.3757e+04,
       1.3799e+04, 1.3843e+04, 1.3863e+04, 1.3935e+04, 1.3965e+04,
       1.4028e+04, 1.4091e+04, 1.4158e+04, 1.4215e+04, 1.4256e+04,
       1.4356e+04, 1.4434e+04, 1.4530e+04, 1.4613e+04, 1.4697e+04,
       1.4778e+04, 1.4821e+04, 1.4924e+04, 1.5026e+04, 1.5124e+04,
       1.5229e+04, 1.5329e+04, 1.5443e+04, 1.5501e+04, 1.5619e+04,
       1.5754e+04, 1.5872e+04, 1.5982e+04, 1.6094e+04, 1.6243e+04,
       1.6316e+04, 1.6453e+04, 1.6600e+04, 1.6698e+04, 1.6842e+04,
       1.6999e+04, 1.7117e+04, 1.7187e+04, 1.7329e+04, 1.7530e+04,
       1.7680e+04, 1.7811e+04, 1.7957e+04, 1.8070e+04, 1.8149e+04,
       1.8310e+04, 1.8429e+04, 1.8537e+04, 1.8677e+04, 1.8797e+04,
       1.8915e+04, 1.8993e+04, 1.9106e+04, 1.9210e+04, 1.9336e+04,
       1.9384e+04, 1.9467e+04, 1.9543e+04, 1.9617e+04, 1.9752e+04,
       1.9856e+04, 1.9987e+04, 2.0089e+04, 2.0177e+04, 2.0251e+04,
       2.0308e+04, 2.0400e+04, 2.0465e+04, 2.0540e+04, 2.0607e+04,
       2.0680e+04, 2.0736e+04, 2.0779e+04, 2.0850e+04, 2.0930e+04,
       2.1022e+04, 2.1105e+04, 2.1189e+04, 2.1265e+04, 2.1323e+04,
       2.1376e+04, 2.1453e+04, 2.1529e+04, 2.1576e+04, 2.1633e+04,
       2.1689e+04, 2.1723e+04, 2.1782e+04, 2.1828e+04, 2.1874e+04,
       2.1913e+04, 2.1940e+04, 2.1977e+04, 2.2007e+04, 2.2034e+04,
       2.2073e+04, 2.2108e+04, 2.2152e+04, 2.2188e+04, 2.2211e+04,
       2.2231e+04, 2.2254e+04, 2.2281e+04, 2.2321e+04, 2.2345e+04,
       2.2379e+04, 2.2408e+04, 2.2427e+04, 2.2452e+04, 2.2469e+04,
       2.2493e+04, 2.2520e+04, 2.2555e+04, 2.2582e+04, 2.2597e+04,
       2.2618e+04, 2.2642e+04, 2.2689e+04, 2.2720e+04, 2.2760e+04,
       2.2781e+04, 2.2811e+04, 2.2848e+04, 2.2888e+04, 2.2928e+04,
       2.2939e+04, 2.2971e+04, 2.3016e+04, 2.3048e+04, 2.3087e+04,
       2.3133e+04, 2.3209e+04, 2.3295e+04, 2.3360e+04, 2.3422e+04,
       2.3462e+04, 2.3529e+04, 2.3575e+04, 2.3635e+04, 2.3702e+04,
       2.3797e+04, 2.3865e+04, 2.3918e+04, 2.4004e+04, 2.4085e+04,
       2.4187e+04, 2.4266e+04, 2.4339e+04, 2.4406e+04, 2.4478e+04,
       2.4573e+04, 2.4639e+04, 2.4713e+04, 2.4783e+04, 2.4848e+04,
       2.4923e+04, 2.5003e+04, 2.5094e+04, 2.5220e+04, 2.5320e+04,
       2.5415e+04, 2.5535e+04, 2.5604e+04, 2.5670e+04, 2.5788e+04,
       2.5889e+04, 2.5978e+04, 2.6035e+04, 2.6114e+04, 2.6175e+04,
       2.6232e+04, 2.6330e+04, 2.6413e+04, 2.6497e+04, 2.6580e+04,
       2.6662e+04, 2.6720e+04, 2.6787e+04, 2.6865e+04, 2.6938e+04,
       2.7004e+04, 2.7072e+04, 2.7135e+04, 2.7206e+04, 2.7246e+04,
       2.7327e+04, 2.7374e+04, 2.7432e+04, 2.7482e+04, 2.7524e+04,
       2.7566e+04, 2.7597e+04, 2.7638e+04, 2.7690e+04, 2.7729e+04,
       2.7785e+04, 2.7831e+04, 2.7866e+04, 2.7893e+04, 2.7947e+04,
       2.7986e+04, 2.8032e+04, 2.8058e+04, 2.8087e+04, 2.8106e+04,
       2.8134e+04, 2.8152e+04, 2.8173e+04, 2.8201e+04, 2.8228e+04,
       2.8252e+04, 2.8269e+04, 2.8280e+04])

## Cleaning And Filtering Data

### Finding missing values

In [66]:
data.isnull().sum()

Date           0
Deaths        15
Recoveries     5
Total          0
dtype: int64

In [67]:
data.shape

(594, 4)

In [50]:
# Droping Column
# data.drop(['Deaths'], axis=1).head()

In [68]:
# Droping null values
data = data.dropna()

In [69]:
data.shape

(579, 4)

In [70]:
data.isnull().sum()

Date          0
Deaths        0
Recoveries    0
Total         0
dtype: int64

In [76]:
data = sns.load_dataset('titanic')
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [77]:
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [79]:
data = data.drop(['deck'], axis=1)

In [81]:
data = data.dropna()
data.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [83]:
data['sex'].value_counts()

male      453
female    259
Name: sex, dtype: int64