In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
# Reading Data
data = pd.read_csv('covid.csv')
data.head()

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations
0,AFG,Asia,Afghanistan,24/02/20,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Exploring Data

In [41]:
data.shape

(183583, 13)

In [42]:
data.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'total_deaths', 'new_deaths', 'total_vaccinations', 'people_vaccinated',
       'people_fully_vaccinated', 'total_boosters', 'new_vaccinations'],
      dtype='object')

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183583 entries, 0 to 183582
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   iso_code                 183583 non-null  object
 1   continent                172860 non-null  object
 2   location                 183583 non-null  object
 3   date                     183583 non-null  object
 4   total_cases              176745 non-null  float64
 5   new_cases                176532 non-null  float64
 6   total_deaths             158467 non-null  float64
 7   new_deaths               158464 non-null  float64
 8   total_vaccinations       50011 non-null   float64
 9   people_vaccinated        47564 non-null   float64
 10  people_fully_vaccinated  45066 non-null   float64
 11  total_boosters           22431 non-null   float64
 12  new_vaccinations         41060 non-null   float64
dtypes: float64(9), object(4)
memory usage: 18.2+ MB

In [44]:
data.describe()

,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations
count,1.767450e+05,1.765320e+05,1.584670e+05,158464.000000,5.001100e+04,4.756400e+04,4.506600e+04,2.243100e+04,4.106000e+04
mean,3.036670e+06,1.242833e+04,6.242540e+04,163.242036,2.074084e+08,1.026395e+08,8.387583e+07,3.111973e+07,1.150450e+06
std,1.898075e+07,8.829878e+04,3.260393e+05,805.517132,9.091703e+08,4.487351e+08,3.823615e+08,1.422240e+08,4.248478e+06
min,1.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
25%,2.459000e+03,0.000000e+00,9.000000e+01,0.000000,7.441225e+05,4.490690e+05,3.449382e+05,1.036050e+04,5.946750e+03
50%,3.261200e+04,7.500000e+01,8.610000e+02,1.000000,5.929734e+06,3.630465e+06,2.874090e+06,8.269670e+05,4.084250e+04
75%,3.539360e+05,1.059000e+03,8.137000e+03,18.000000,3.699011e+07,2.097199e+07,1.727424e+07,6.528614e+06,2.794522e+05
max,5.149754e+08,4.089131e+06,6.240940e+06,18144.000000,1.162462e+10,5.151278e+09,4.668004e+09,1.877161e+09,5.450643e+07

In [45]:
# Droping 'iso_code' column because it is useless for us
data = data.drop(['iso_code'], axis=1)
data.head()

,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations
0,Asia,Afghanistan,24/02/20,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Asia,Afghanistan,25/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Asia,Afghanistan,26/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Asia,Afghanistan,27/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Asia,Afghanistan,28/02/20,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
data.isnull().sum()

continent                   10723
location                        0
date                            0
total_cases                  6838
new_cases                    7051
total_deaths                25116
new_deaths                  25119
total_vaccinations         133572
people_vaccinated          136019
people_fully_vaccinated    138517
total_boosters             161152
new_vaccinations           142523
dtype: int64

In [47]:
data.keys()[3:]

Index(['total_cases', 'new_cases', 'total_deaths', 'new_deaths',
       'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
       'total_boosters', 'new_vaccinations'],
      dtype='object')

In [51]:
# Replacing empty cells from 'total_cases' to 'new_vaccinations' with 0
for key in data.keys()[3:]:
    print(key)
    data[key].fillna(0, inplace=True)

total_cases
new_cases
total_deaths
new_deaths
total_vaccinations
people_vaccinated
people_fully_vaccinated
total_boosters
new_vaccinations

In [52]:
data.isnull().sum()

continent                  10723
location                       0
date                           0
total_cases                    0
new_cases                      0
total_deaths                   0
new_deaths                     0
total_vaccinations             0
people_vaccinated              0
people_fully_vaccinated        0
total_boosters                 0
new_vaccinations               0
dtype: int64