In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
# Reading Data
data = pd.read_csv('population.csv')
data.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 1: invalid continuation byte

### Exploring Data

In [3]:
data.shape

(988, 14)

In [4]:
data.columns

Index(['Domain Code', 'Domain', 'Area Code (FAO)', 'Area', 'Element Code',
       'Element', 'Item Code (FAO)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       988 non-null    object
 1   Domain            988 non-null    object
 2   Area Code (FAO)   988 non-null    int64
 3   Area              988 non-null    object
 4   Element Code      988 non-null    int64
 5   Element           988 non-null    object
 6   Item Code (FAO)   988 non-null    int64
 7   Item              988 non-null    object
 8   Year Code         988 non-null    int64
 9   Year              988 non-null    int64
 10  Unit              988 non-null    object
 11  Value             988 non-null    int64
 12  Flag              15 non-null     object
 13  Flag Description  988 non-null    object
dtypes: int64(6), object(8)
memory usage: 108.2+ KB

In [6]:
data.describe()

,Area Code (FAO),Element Code,Item Code (FAO),Year Code,Year,Value
count,988.0,988.000000,988.000000,988.0,988.0,9.880000e+02
mean,165.0,5753.487854,554.558704,2018.0,2018.0,3.998367e+04
std,0.0,149.674618,347.582882,0.0,0.0,2.476227e+05
min,165.0,5607.000000,15.000000,2018.0,2018.0,0.000000e+00
25%,165.0,5610.000000,249.000000,2018.0,2018.0,2.375000e+01
50%,165.0,5622.000000,526.000000,2018.0,2018.0,4.335000e+02
75%,165.0,5910.000000,837.000000,2018.0,2018.0,5.364250e+03
max,165.0,5922.000000,1296.000000,2018.0,2018.0,3.912607e+06

In [8]:
data.columns

Index(['Domain Code', 'Domain', 'Area Code (FAO)', 'Area', 'Element Code',
       'Element', 'Item Code (FAO)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description'],
      dtype='object')

In [11]:
data.groupby("Element").mean()

,Area Code (FAO),Element Code,Item Code (FAO),Year Code,Year,Value
Element,,,,,,
Export Quantity,165.0,5909.942982,561.912281,2018.0,2018.0,66160.644737
Export Value,165.0,5922.000000,558.151111,2018.0,2018.0,29068.733333
Import Quantity,165.0,5609.951673,551.702602,2018.0,2018.0,38289.509294
Import Value,165.0,5622.000000,548.105263,2018.0,2018.0,28492.078947